apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base
  - ../istio

configMapGenerator:
  - literals:
      - TITLE="Blue Parrot"
      - IMAGE="parrot-1.jpg"
    name: blue
    namespace: parrot
  - literals:
      - TITLE="Green Parrot"
      - IMAGE="parrot-2.jpg"
    name: green
    namespace: parrot
  
patchesStrategicMerge:
  - patch.yaml
