apiVersion: apps/v1
kind: Deployment
metadata:
  name: parrot-blue
  namespace: parrot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: parrot-blue
      version: blue
  template:
    metadata:
      labels:
        app: parrot-blue
        version: blue
    spec:
      containers:
        - name: parrot-blue
          image: 533267286761.dkr.ecr.us-east-1.amazonaws.com/parrot:1
          ports:
            - containerPort: 3000
          env:
            - name: TITLE
              valueFrom:
                configMapKeyRef:
                  name: blue
                  key: TITLE
            - name: IMAGE
              valueFrom:
                configMapKeyRef:
                  name: blue
                  key: IMAGE
