apiVersion: v1
kind: Service
metadata:
  name: parrot-green
  namespace: parrot
spec:
  selector:
    app: parrot
    version: green
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000

