apiVersion: apps/v1
kind: Deployment
metadata:
  name: parrot-blue
  namespace: parrot
spec:
  selector:
    matchLabels:
      app: parrot-blue
  template:
    spec:
      containers:
        - name: parrot-blue
          resources:
            requests:
              memory: 300Mi
              cpu: 300m
            limits:
              memory: 400Mi
              cpu: 400m
          image: 058264241924.dkr.ecr.us-east-1.amazonaws.com/parrot:9
          ports:
            - containerPort: 3000