# This pipeline will run that builds and deploys the poc-healthcare-payer-demo-app docker container any time a PR is Raised and Merged against "Main" Branch.
name: build-and-push
on:
  push:
    branches:
      - main #This name is temporary meanwhile Tatiane rename this branch.

# Used for getting permissions to AWS resources through an OIDC federation
permissions:
  id-token: write
  contents: read  

env:
  AWS_REGION: ca-central-1
  AWS_ACCOUNT: ${{ secrets.AWS_ACCOUNT }}
  ECR_REPO: parrot

jobs:
  build:
    runs-on: ubuntu-latest
    steps:                       
      # Configure AWS credentials using assumed role
      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1.7.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - uses: actions/checkout@v2                  
      - name: Login to ECR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }} ##image

      - name: Create ECR public repository if it does not exist
        run: |
          REPO_NAME=${{ env.ECR_REPO }}
          aws ecr-public describe-repositories --repository-names $REPO_NAME --region ${{ env.AWS_REGION }} || \
          aws ecr-public create-repository --repository-name $REPO_NAME --region ${{ env.AWS_REGION }}

      - name: Docker Build and Publish
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:${{github.run_number}}