name: Install Istio

on:
  workflow_dispatch:
    inputs:
      ISTIO_VERSION:
        description: 'Istio version'
        required: true
        default: '1.22.0'
      CLUSTER_NAME:
        description: 'EKS cluster name'
        required: true
        default: 'K8S-Blue-Green'
      REGION:
        description: 'AWS region'
        required: true
        default: 'us-east-1'

jobs:
  install-istio:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "ISTIO_VERSION=${{ github.event.inputs.ISTIO_VERSION }}" >> $GITHUB_ENV
        echo "CLUSTER_NAME=${{ github.event.inputs.CLUSTER_NAME }}" >> $GITHUB_ENV
        echo "REGION=${{ github.event.inputs.REGION }}" >> $GITHUB_ENV

    - name: 'Configure AWS credentials'
      uses: aws-actions/configure-aws-credentials@v1.7.0
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.REGION }}

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y curl jq

    - name: Install eksctl 
      run: |
        ARCH=amd64
        PLATFORM=$(uname -s)_$ARCH
        curl -sLO "https://github.com/eksctl-io/eksctl/releases/latest/download/eksctl_$PLATFORM.tar.gz"
        tar -xzf eksctl_$PLATFORM.tar.gz -C /tmp && rm eksctl_$PLATFORM.tar.gz
        sudo mv /tmp/eksctl /usr/local/bin

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Install aws-iam-authenticator
      run: |
        curl -o aws-iam-authenticator https://amazon-eks.s3.us-west-2.amazonaws.com/1.18.9/2020-11-02/bin/linux/amd64/aws-iam-authenticator
        chmod +x ./aws-iam-authenticator
        sudo mv aws-iam-authenticator /usr/local/bin

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name ${{ env.CLUSTER_NAME }} --region ${{ env.REGION }}

    - name: Download and install Istio
      run: |
        curl -L https://istio.io/downloadIstio | ISTIO_VERSION=${{ env.ISTIO_VERSION }} TARGET_ARCH=x86_64 sh -
        export PATH=$PWD/istio-${{ env.ISTIO_VERSION }}/bin:$PATH
        echo "PATH=$PWD/istio-${{ env.ISTIO_VERSION }}/bin:$PATH" >> $GITHUB_ENV
        istioctl version

    - name: Associate IAM OIDC provider
      run: |
        eksctl utils associate-iam-oidc-provider --region ${{ env.REGION }} --cluster ${{ env.CLUSTER_NAME }} --approve

    - name: Install Istio base chart
      run: istioctl install --set profile=demo -y

    - name: Verify installation
      run: kubectl get pods -n istio-
    
    - name: Install Kiali
      run: kubectl apply -f https://raw.githubusercontent.com/istio/istio/release-1.22/samples/addons/kiali.yaml
    


    
