apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
  - ../../istio

configMapGenerator:
  - literals:
      - TITLE="Green Parrot"
      - IMAGE="parrot-2.jpg"
    name: green
    namespace: parrot
  
patchesStrategicMerge:
  - patch.yaml
